//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationCompany.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTariff
    {
        public int ClientTariffId { get; set; }
        public int UserId { get; set; }
        public int TariffId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Tariff Tariff { get; set; }
        public virtual User User { get; set; }
    }
}
